columns:
-   description: A unique identifier for each passenger
    name: id
    data_schema:
        dtype: int
    tags:
    - unique_identifier
-   description: Whether the passenger survived or not
    name: survived
    data_schema:
        dtype: int
    tags:
    - target
-   description: The class of the passenger
    name: pclass
    data_schema:
        dtype: int
    tags:
    - raw_feature
    - model_feature
-   description: The full name of the passenger
    name: name
    data_schema:
        dtype: str
    tags:
    - metadata
-   description: The sex of the passenger
    name: sex
    data_schema:
        dtype: str
    tags:
    - raw_feature
    - model_feature
-   description: The age of the passenger
    name: age
    data_schema:
        dtype: float
        nullable: true
    tags:
    - raw_feature
    - model_feature
-   description: The total number of the passengers' siblings and spouse
    name: sibsp
    data_schema:
        dtype: int
    tags:
    - raw_feature
    - model_feature
-   description: The total number of the passengers' parents and children
    name: parch
    data_schema:
        dtype: int
    tags:
    - raw_feature
    - model_feature
-   description: The ticket number for that passenger
    name: ticket
    data_schema:
        dtype: str
    tags:
    - metadata
-   description: The cabin the passenger stayed in
    name: cabin
    data_schema:
        dtype: str
        nullable: true
    tags:
    - raw_feature
    - model_feature
-   description: The port the passenger embarked from
    name: embarked
    data_schema:
        dtype: str
        nullable: true
    tags:
    - raw_feature
    - model_feature
-   description: The fare the passenger paid
    name: fare
    data_schema:
        dtype: float
        nullable: true
    tags:
    - raw_feature
    - model_feature
-   description: Number of cabins the passenger and family had
    name: number_of_cabins
    data_schema:
        dtype: int
    tags:
    - derived_feature
    - model_feature
name: titanic_modelling_data
